######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 11 12:50:25 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += /usr/realtime/include	

# Input
HEADERS += apframe.h apthread.h reticap.h ../acq_common.h
SOURCES += main.cpp
