######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 26 18:18:49 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += /usr/realtime/include

# Input
HEADERS += apframe.h apthread.h reticap.h ../acq_common.h
SOURCES += main.cpp
